<a href="https://colab.research.google.com/github/VB156/ACA-final-project/blob/main/VikaItayDataMining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import datetime
import os
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

First time for anything, huh? This code should run only once. If it's commented, leave it commented

In [2]:
# from google.colab import drive
# drive.mount('/content/drive')

Data Analysis

In [4]:
os.chdir('/content')
churn = pd.read_csv('churn_dataset_train.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'churn_dataset_train.csv'

In [ ]:
# Okay let's make sure there are no 'weird' values in all of the columns...
for col in churn.select_dtypes(include=np.number).columns:
    print(f"{col}:")
    print(f"  Nulls: {churn[col].isnull().sum()}")
    print(f"  Min/Max: {churn[col].min()}, {churn[col].max()}")
    print(f"  Unique: {churn[col].nunique()}")
    print(f"  Outliers: {(np.abs((churn[col] - churn[col].mean()) / churn[col].std()) > 3).sum()} rows beyond 3 std devs\n")
for col in churn.select_dtypes(include='object').columns:
    print(f"{col}:")
    print(f"  Nulls: {churn[col].isnull().sum()}")
    print(f"  Unique: {churn[col].nunique()} → {churn[col].unique()[:10]}")

Unnamed: 0:
  Nulls: 0
  Min/Max: 0, 36989
  Unique: 24784
  Outliers: 0 rows beyond 3 std devs

age:
  Nulls: 0
  Min/Max: 10, 64
  Unique: 55
  Outliers: 0 rows beyond 3 std devs

days_since_last_login:
  Nulls: 0
  Min/Max: -999, 26
  Unique: 27
  Outliers: 1352 rows beyond 3 std devs

avg_time_spent:
  Nulls: 0
  Min/Max: -2281.236526, 3040.41
  Unique: 18859
  Outliers: 540 rows beyond 3 std devs

avg_transaction_value:
  Nulls: 0
  Min/Max: 800.46, 99914.05
  Unique: 24741
  Outliers: 477 rows beyond 3 std devs

points_in_wallet:
  Nulls: 2287
  Min/Max: -549.3574977, 1816.933696
  Unique: 17548
  Outliers: 398 rows beyond 3 std devs

churn:
  Nulls: 0
  Min/Max: 0, 1
  Unique: 2
  Outliers: 0 rows beyond 3 std devs

customer_id:
  Nulls: 0
  Unique: 24784 → ['fffe43004900440033003200390032003400'
 'fffe43004900440036003200310038003600' 'fffe430049004400350032003200'
 'fffe43004900440032003200380034003600'
 'fffe43004900440035003600320032003100'
 'fffe43004900440034003500300038003800'
 'fffe43004900440033003400340030003800'
 'fffe43004900440036003200380037003800'
 'fffe43004900440031003500300038003900'
 'fffe43004900440034003700300037003100']
Name:
  Nulls: 0
  Unique: 24784 → ['Dusty Dunneback' 'Dorine Vanduyn' 'Christene Pulver' 'Brendan Enciso'
 'Lizette Lemons' 'Vera Hartzler' 'Minerva Emmons' 'Ming Shealy'
 'Madalyn Aumick' 'Gina Piermarini']
gender:
  Nulls: 0
  Unique: 3 → ['F' 'M' 'Unknown']
security_no:
  Nulls: 0
  Unique: 24784 → ['URPJZ5B' 'O0IWUYW' '2R0EFA2' 'XF0YGUT' 'V5YZC2N' '6PI2Y1B' 'NC94WL3'
 'F8RLNDC' 'S0CE1NE' 'C2VAPSR']
region_category:
  Nulls: 3697
  Unique: 3 → ['Village' 'City' 'Town' nan]
membership_category:
  Nulls: 0
  Unique: 6 → ['No Membership' 'Silver Membership' 'Basic Membership' 'Gold Membership'
 'Platinum Membership' 'Premium Membership']
joining_date:
  Nulls: 0
  Unique: 1096 → ['09/08/2017' '09/02/2016' '11/06/2017' '16/07/2017' '15/02/2017'
 '11/12/2016' '03/06/2015' '31/12/2015' '08/04/2017' '20/07/2016']
joined_through_referral:
  Nulls: 3626
  Unique: 2 → ['Yes' 'No' nan]
referral_id:
  Nulls: 11997
  Unique: 8738 → ['CID49268' nan 'CID23438' 'CID16576' 'CID63534' 'CID30764' 'CID10555'
 'CID42424' 'CID16058' 'CID17601']
preferred_offer_types:
  Nulls: 208
  Unique: 3 → ['Gift Vouchers/Coupons' 'Credit/Debit Card Offers' 'Without Offers' nan]
medium_of_operation:
  Nulls: 3628
  Unique: 3 → ['Desktop' 'Smartphone' nan 'Both']
internet_option:
  Nulls: 0
  Unique: 3 → ['Mobile_Data' 'Wi-Fi' 'Fiber_Optic']
avg_frequency_login_days:
  Nulls: 0
  Unique: 1110 → ['24' '27' 'Error' '14' '13' '29' '11' '26' '6' '8']
used_special_discount:
  Nulls: 0
  Unique: 2 → ['Yes' 'No']
offer_application_preference:
  Nulls: 0
  Unique: 2 → ['No' 'Yes']
past_complaint:
  Nulls: 0
  Unique: 2 → ['No' 'Yes']
complaint_status:
  Nulls: 0
  Unique: 5 → ['Not Applicable' 'No Information Available' 'Unsolved'
 'Solved in Follow-up' 'Solved']
feedback:
  Nulls: 0
  Unique: 9 → ['Poor Product Quality' 'Too many ads' 'No reason specified'
 'Products always in Stock' 'Poor Customer Service' 'Reasonable Price'
 'User Friendly Website' 'Poor Website' 'Quality Customer Care']

Data Preprocessing

In [ ]:
# These are obviously non-informative, or they are strings which we can't really work with:
irrelevant_cols = ['Unnamed: 0', 'customer_id', 'Name', 'security_no', 'referral_id', 'past_complaint', 'complaint_status']
for c in irrelevant_cols:
  churn = churn.drop(c, axis=1)
churn.head()

,age,gender,region_category,membership_category,joining_date,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,feedback,churn
0,30,F,Village,No Membership,09/08/2017,Yes,Gift Vouchers/Coupons,Desktop,Mobile_Data,20,118.390000,10579.56,24,610.360000,Yes,No,Poor Product Quality,1
1,55,M,Village,Silver Membership,09/02/2016,No,Credit/Debit Card Offers,Smartphone,Wi-Fi,15,179.420000,22963.05,27,694.650000,Yes,No,Poor Product Quality,0
2,47,M,City,Basic Membership,11/06/2017,Yes,Credit/Debit Card Offers,NaN,Wi-Fi,23,42.230000,32604.41,Error,520.620000,Yes,No,Poor Product Quality,1
3,18,M,Town,Gold Membership,09/02/2016,No,Credit/Debit Card Offers,Desktop,Mobile_Data,7,-1035.833706,48913.61,27,1150.093442,Yes,No,Too many ads,0
4,28,F,City,No Membership,16/07/2017,Yes,Credit/Debit Card Offers,Both,Fiber_Optic,10,449.770000,20010.02,14,653.040000,Yes,Yes,No reason specified,0

In [ ]:
# These require some editing:
print(f"Before: {set(churn['gender'].values)}")
churn = churn[churn['gender'] != 'Unknown'].reset_index()
print(f"After: {set(churn['gender'].values)}")
print(f"Before: {churn['joining_date'][0:5]}")
for i in range(len(churn['joining_date'])):
  churn.loc[i,'joining_date'] = abs((pd.to_datetime(churn.loc[i,'joining_date'], format='%d/%m/%Y') - datetime.datetime.today()).days)
print(f"After: {churn['joining_date'][0:5]}")
print(f"Before: {set(churn['medium_of_operation'].values)}, {set(churn['joined_through_referral'].values)}")
churn = churn.dropna()
print(f"After: {set(churn['medium_of_operation'].values)}, {set(churn['joined_through_referral'].values)}")
print(f"Before: {set(churn['avg_frequency_login_days'].values)}")
churn = churn[churn['avg_frequency_login_days'] != 'Error'].reset_index()
print(f"After: {set(churn['avg_frequency_login_days'].values)}")

Before: {'M', 'F', 'Unknown'}
After: {'M', 'F'}
Before: 0    09/08/2017
1    09/02/2016
2    11/06/2017
3    09/02/2016
4    16/07/2017
Name: joining_date, dtype: object
After: 0    2821
1    3368
2    2880
3    3368
4    2845
Name: joining_date, dtype: object
Before: {'Desktop', nan, 'Smartphone', 'Both'}, {'No', nan, 'Yes'}
After: {'Desktop', 'Smartphone', 'Both'}, {'No', 'Yes'}
Before: {'9', '37.57986594', '40.28262011', '49.36101144', '-8.68185081', '-9.683109495', '29.91835673', '50.64895275', '-5.938582549', '-10.10118954', '41.16266368', '-4.622815409', '29.16584426', '41.58210116', '4.123505593', '28.16282391', '2.49891818', '39.93003268', '-8.104517563', '43.11808015', '0.740084813', '29', '-17.07762543', '39.01260915', '-15.19906384', '49.70530762', '3', '-19.03426612', '25.91157636', '31.96578356', '-13.76815838', '-10.05103279', '33.22209825', '35.89934266', '47.74895186', '-9.014644272', '-7.384860972', '43.78725707', '15', '-7.771873798', '34.32765303', '-13.55840129', '43.55615989', '-20.43222547', '-22.27092071', '3.658763026', '36.93542913', '32.46020929', '3.803723614', '44.03257204', '0.539882592', '-9.618914459', '35.36276526', '47.19238609', '41.84419523', '33.49112462', '-9.374147648', '-14.6865235', '28.84957954', '-19.67109513', '-16.2601583', '39.9543901', '-0.945190399', '-11.66844478', '28.76584817', '-1.858115496', '-15.55875102', '-17.81408994', '-10.27005345', '-16.01285303', '37.57759299', '-11.13882368', '33.77474697', '41.55035088', '47.25127151', '-0.86185647', '-7.42866665', '-3.80475801', '-9.746530558', '-1.781382527', '36.48833114', '-19.72394757', '-14.19770947', '36.34339123', '-18.52361838', '35.73749417', '35.97913237', '-5.373348278', '-6.975997099', '35.03140549', '-3.406843317', '46.43232755', '-0.550838449', '28', '35.90203976', '-16.76052245', '-9.297071675', '39.16663275', '-4.025399087', '36.53426332', '38.00321797', '6.775741075', '1.825074286', '20.47079749', '42.52885148', '35.89847758', '-3.482661715', '40.60196525', '24', '3.342992951', '-10.35654909', '40.0455936', '-8.41839053', '-9.650151656', '30.56047807', '43.28621016', '-3.172924622', '33.67011622', '49.62913718', '-16.75001624', '-10.64983246', '-20.2434403', '19.10848608', '41.65958885', '3.604420744', '-7.37907299', '-20.87210501', '0.949579361', '26.9866273', '31.48239211', '45.32819088', '54.67774554', '33.73249873', '46.79574896', '45.61696321', '-6.69962403', '-19.21786241', '33.02737933', '46.43606503', '32.95058798', '-10.72921303', '-2.330857588', '-12.98924753', '2.6142143', '-15.6435663', '35.56159195', '-6.596258877', '-1.875372955', '41.8989998', '46.83217981', '-20.3943083', '-16.36841798', '32.87229351', '39.53564335', '31.24524404', '43.42346986', '-20.76148832', '-13.57329646', '5.591050517', '35.34940976', '-15.24027847', '1', '38.34424268', '47.79911883', '42.6930255', '38.87621543', '2.173242412', '-13.72053844', '43.69016354', '30', '31.60351268', '31.66643652', '2.758644582', '-3.745632068', '-11.06819025', '-12.69062811', '35.03341048', '46.53321064', '54.70909174', '-2.152655791', '46.44393053', '-2.291846209', '44.71733942', '-7.662559135', '-3.006770944', '44.1692614', '-4.275635704', '-5.788321938', '-17.57234938', '43.84329959', '17', '-17.24588134', '45.74302566', '0.113511045', '34.70278383', '41.92131412', '44.59829873', '39.63339862', '-14.68954871', '23', '-3.675920257', '6', '47.5752315', '-3.919990596', '-17.79258804', '32.4177354', '-12.42666077', '48.684418', '-5.347636778', '36.61334172', '-20.35135008', '43.86709938', '-16.32931258', '16.24538222', '54.31463505', '-22.18205764', '-3.161503304', '8', '-16.47618959', '3.038059449', '-15.75327922', '-12.49321284', '-14.12401512', '-10.15017275', '35.50632878', '-7.044123324', '-23.92071268', '37.80476338', '47.45683607', '-6.13453171', '52.72486204', '43.60324168', '-5.494495412', '-10.85586317', '35.85890869', '-9.234516364', '-13.66950881', '-7.280566124', '36.14594778', '-15.89405063', '2', '40.7352632', '-0.752430937', '-12.85234884', '33.48479039', '-8.467490594', '-14.65233124', '-21.6215658', '40.16776268', 'Error', '30.82641503', '33.50649937', '12', '41.32446694', '32.70160438', '35.53441832', '-5.585924221', '37.43718334', '37.60412159', '34.68828596', '2.930569167', '-10.69917281', '-4.366406801', '1.962197501', '55.12785548', '-17.60242493', '52.83406193', '52.44215935', '-6.530688802', '-13.77679803', '-0.789694924', '-7.317388817', '37.22794614', '-22.98148263', '50.90101012', '-10.58501441', '31.64986541', '31.40571165', '-8.38834673', '35.56432328', '31.05679504', '13', '2.759553158', '-3.37147201', '38.47159929', '28.02977091', '47.61570675', '-14.16478236', '-11.13645755', '-4.528299184', '-3.530456584', '36.61576543', '52.24936027', '-9.575539815', '44.67852041', '-20.34386328', '32.539527', '51.47945809', '50.7174312', '-17.76016117', '-14.60558893', '43.23157761', '31.64130009', '38.79712159', '-1.092465928', '54.75374649', '31.28963036', '1.946183913', '-14.09388968', '0.671784262', '-15.33210224', '45.66402805', '-9.180950939', '39.2063087', '40.44123057', '-18.90536167', '-28.59201152', '29.19245072', '51.83557874', '43.31513154', '20', '7', '38.31000086', '6.655431836', '31.25687493', '0.0092081', '47.83384288', '45.88252063', '-8.104700315', '26.36800606', '38.70904695', '-13.3563073', '43.98148843', '39.73890372', '32.1722058', '2.970222429', '3.128513373', '33.99952277', '42.5542478', '-13.64684955', '2.276130431', '-24.37954914', '4', '35.74978206', '37.68112237', '41.00078923', '55.01616857', '-2.07197427', '17.65581603', '-10.79019272', '-10.18661474', '-5.190864906', '16', '-14.91504623', '4.842593978', '52.22993661', '-3.859804404', '48.6096123', '-16.91683516', '-2.659304921', '-16.69464162', '51.438905', '55.37627229', '-4.202424119', '35.20834139', '22', '36.33902857', '45.67270986', '26', '-10.1884666', '-1.980458618', '-11.85678262', '33.35548294', '50.10702717', '48.93454967', '10', '4.563792219', '-19.31163198', '28.75639925', '-18.45761877', '33.252666', '-9.248903191', '34.36540071', '47.53562904', '45.7108634', '52.17415927', '30.54990502', '28.35374278', '-16.36076112', '46.88925783', '43.3538644', '-35.81575763', '-18.90265867', '-1.581181915', '36.14118992', '38.27589013', '51.94390501', '47.61306649', '-0.399995771', '11', '34.55468895', '-10.36261454', '-9.778056242', '53.84940846', '53.13233119', '-23.66800444', '51.22937117', '-10.14068384', '-6.496195902', '29.57142745', '-2.666803669', '28.04306149', '25', '-24.70043508', '40.27880968', '29.78610668', '42.95640301', '-18.90112282', '-10.97015456', '-8.25481245', '-9.638801336', '-9.909440925', '35.40233875', '35.30980323', '35.73926206', '35.52394706', '-3.761889863', '39.38316934', '-13.34126151', '-2.475368771', '42.56993205', '28.91053504', '32.92979253', '39.25410903', '-0.871723653', '-15.82168209', '5.517470006', '29.5304898', '33.02434314', '42.84685687', '0.257630327', '-0.2228234', '45.92999947', '46.44566382', '43.65486147', '48.3823364', '51.47143749', '26.49138841', '38.85279954', '2.754193798', '37.19396132', '42.98639722', '-43.62541346', '54.17323366', '32.07700035', '30.60813248', '-11.08318958', '-20.24794729', '52.04800248', '-11.52636513', '35.0621461', '-20.58731044', '-11.09874064', '-18.31117447', '37.21403232', '-18.43232957', '0.548998137', '-8.35102561', '34.54408249', '-1.198008932', '44.82688768', '-11.90352158', '3.207385793', '3.389625544', '30.3054997', '-16.29992418', '-17.67422239', '-5.472423489', '2.727734601', '39.40515161', '45.84513865', '11.19661971', '40.66717303', '-10.1288288', '31.14011906', '-11.33699198', '42.9515239', '-5.798711676', '27.46325843', '49.85514063', '40.52615255', '-13.85555813', '33.28431211', '42.4731373', '-3.431106621', '5', '-7.047265034', '39.48706023', '-2.398700357', '39.06824636', '-1.020500027', '18', '-12.44113808', '-18.05418907', '50.23826213', '10.4216168', '-34.41711527', '44.93176428', '36.18907426', '-9.623062254', '44.28870818', '-1.005268319', '-13.19863186', '-18.69235271', '45.04989173', '-18.78687984', '41.96855078', '40.17907614', '40.44853118', '50.14234501', '21', '7.042916198', '26.38273342', '37.93297382', '54.64598899', '1.083764946', '-6.260290804', '-16.36458931', '-19.80939099', '50.02946976', '44.29441699', '-2.105071957', '-5.519855665', '38.83289665', '-22.010069', '46.46931572', '-24.54882343', '46.94646266', '54.60574916', '37.58843647', '19', '-16.2608971', '14', '-6.928265517', '52.2948916', '1.234738899', '36.40081388', '-6.402224494', '50.3499744', '43.45032795', '51.2561959', '35.77617642', '-19.73127299', '1.63488693', '32.19093588', '38.66234412', '33.82554794', '38.05212158', '49.11875923', '-13.83650197', '51.86558858', '4.852623072', '24.42621636', '34.03490791', '-0.006221399', '-5.654516348', '35.16293041', '52.45029642', '-5.058123274', '38.81388653', '44.01452226', '14.73466935', '31.49879061', '-13.46086848', '36.89955403', '42.35696751', '-7.99445065', '-2.436277763', '48.33046835', '-17.66506344', '-6.36445797', '0.64365928', '51.81780671', '49.75987134', '35.19637699', '49.7904402', '27', '30.98682419', '-11.85156251', '-19.81338725', '-5.990044826', '-0.368576054', '29.27665737', '40.08906458', '40.47299251', '-12.90639375', '53.87618817', '48.19475105', '37.62578923', '-0.198479563', '-3.740018248', '-15.62939639', '52.89309985', '36.10909204', '-11.26775596', '2.433838527', '-16.77810004', '-12.74286445', '32.5067075', '56.16197924', '-12.82889011', '26.54510508', '-21.03731536', '53.15301711', '-11.02995096', '-23.46838168', '49.62575011', '-7.537387378', '-17.07968464', '-7.203747536', '40.58911719', '-9.154338862', '34.79245568', '29.54521074', '-20.36921386', '33.36786974', '45.71683637', '-7.192078843', '-0.047392668', '-19.03033588', '-18.51869077', '-10.88298552', '-4.407431283', '32.73344278', '38.45623068', '32.56652488'}
After: {'9', '37.57986594', '40.28262011', '49.36101144', '-8.68185081', '-9.683109495', '29.91835673', '50.64895275', '-5.938582549', '-10.10118954', '41.16266368', '-4.622815409', '29.16584426', '41.58210116', '4.123505593', '28.16282391', '2.49891818', '39.93003268', '-8.104517563', '43.11808015', '0.740084813', '29', '-17.07762543', '39.01260915', '-15.19906384', '49.70530762', '3', '-19.03426612', '25.91157636', '31.96578356', '-13.76815838', '-10.05103279', '33.22209825', '35.89934266', '47.74895186', '-9.014644272', '-7.384860972', '43.78725707', '15', '-7.771873798', '34.32765303', '-13.55840129', '43.55615989', '-20.43222547', '-22.27092071', '3.658763026', '36.93542913', '32.46020929', '3.803723614', '44.03257204', '0.539882592', '-9.618914459', '35.36276526', '47.19238609', '41.84419523', '33.49112462', '-9.374147648', '-14.6865235', '28.84957954', '-19.67109513', '-16.2601583', '39.9543901', '-0.945190399', '-11.66844478', '28.76584817', '-1.858115496', '-15.55875102', '-17.81408994', '-10.27005345', '-16.01285303', '37.57759299', '-11.13882368', '33.77474697', '41.55035088', '47.25127151', '-0.86185647', '-7.42866665', '-3.80475801', '-9.746530558', '-1.781382527', '36.48833114', '-19.72394757', '-14.19770947', '36.34339123', '-18.52361838', '35.73749417', '35.97913237', '-5.373348278', '-6.975997099', '35.03140549', '-3.406843317', '46.43232755', '-0.550838449', '28', '35.90203976', '-16.76052245', '-9.297071675', '39.16663275', '-4.025399087', '36.53426332', '38.00321797', '6.775741075', '1.825074286', '20.47079749', '42.52885148', '35.89847758', '-3.482661715', '40.60196525', '24', '3.342992951', '-10.35654909', '40.0455936', '-8.41839053', '-9.650151656', '30.56047807', '43.28621016', '-3.172924622', '33.67011622', '49.62913718', '-16.75001624', '-10.64983246', '-20.2434403', '19.10848608', '41.65958885', '3.604420744', '-7.37907299', '-20.87210501', '0.949579361', '26.9866273', '31.48239211', '45.32819088', '54.67774554', '33.73249873', '46.79574896', '45.61696321', '-6.69962403', '-19.21786241', '33.02737933', '46.43606503', '32.95058798', '-10.72921303', '-2.330857588', '-12.98924753', '2.6142143', '-15.6435663', '35.56159195', '-6.596258877', '-1.875372955', '41.8989998', '46.83217981', '-20.3943083', '-16.36841798', '32.87229351', '39.53564335', '31.24524404', '43.42346986', '-20.76148832', '-13.57329646', '5.591050517', '35.34940976', '-15.24027847', '1', '38.34424268', '47.79911883', '42.6930255', '38.87621543', '2.173242412', '-13.72053844', '43.69016354', '30', '31.60351268', '31.66643652', '2.758644582', '-3.745632068', '-11.06819025', '-12.69062811', '35.03341048', '46.53321064', '54.70909174', '-2.152655791', '46.44393053', '-2.291846209', '44.71733942', '-7.662559135', '-3.006770944', '44.1692614', '-4.275635704', '-5.788321938', '-17.57234938', '43.84329959', '17', '-17.24588134', '45.74302566', '0.113511045', '34.70278383', '41.92131412', '44.59829873', '39.63339862', '-14.68954871', '23', '-3.675920257', '6', '47.5752315', '-3.919990596', '-17.79258804', '32.4177354', '-12.42666077', '48.684418', '-5.347636778', '36.61334172', '-20.35135008', '43.86709938', '-16.32931258', '16.24538222', '54.31463505', '-22.18205764', '-3.161503304', '8', '-16.47618959', '3.038059449', '-15.75327922', '-12.49321284', '-14.12401512', '-10.15017275', '35.50632878', '-7.044123324', '-23.92071268', '37.80476338', '47.45683607', '-6.13453171', '52.72486204', '43.60324168', '-5.494495412', '-10.85586317', '35.85890869', '-9.234516364', '-13.66950881', '-7.280566124', '36.14594778', '-15.89405063', '2', '40.7352632', '-0.752430937', '-12.85234884', '33.48479039', '-8.467490594', '-14.65233124', '-21.6215658', '40.16776268', '30.82641503', '33.50649937', '12', '41.32446694', '32.70160438', '35.53441832', '-5.585924221', '37.43718334', '37.60412159', '34.68828596', '2.930569167', '-10.69917281', '-4.366406801', '1.962197501', '55.12785548', '-17.60242493', '52.83406193', '52.44215935', '-6.530688802', '-13.77679803', '-0.789694924', '-7.317388817', '37.22794614', '-22.98148263', '50.90101012', '-10.58501441', '31.64986541', '31.40571165', '-8.38834673', '35.56432328', '31.05679504', '13', '2.759553158', '-3.37147201', '38.47159929', '28.02977091', '47.61570675', '-14.16478236', '-11.13645755', '-4.528299184', '-3.530456584', '36.61576543', '52.24936027', '-9.575539815', '44.67852041', '-20.34386328', '32.539527', '51.47945809', '50.7174312', '-17.76016117', '-14.60558893', '43.23157761', '31.64130009', '38.79712159', '-1.092465928', '54.75374649', '31.28963036', '1.946183913', '-14.09388968', '0.671784262', '-15.33210224', '45.66402805', '-9.180950939', '39.2063087', '40.44123057', '-18.90536167', '-28.59201152', '29.19245072', '51.83557874', '43.31513154', '20', '7', '38.31000086', '6.655431836', '31.25687493', '0.0092081', '47.83384288', '45.88252063', '-8.104700315', '26.36800606', '38.70904695', '-13.3563073', '43.98148843', '39.73890372', '32.1722058', '2.970222429', '3.128513373', '33.99952277', '42.5542478', '-13.64684955', '2.276130431', '-24.37954914', '4', '35.74978206', '37.68112237', '41.00078923', '55.01616857', '-2.07197427', '17.65581603', '-10.79019272', '-10.18661474', '-5.190864906', '16', '-14.91504623', '4.842593978', '52.22993661', '-3.859804404', '48.6096123', '-16.91683516', '-2.659304921', '-16.69464162', '51.438905', '55.37627229', '-4.202424119', '35.20834139', '22', '36.33902857', '45.67270986', '26', '-10.1884666', '-1.980458618', '-11.85678262', '33.35548294', '50.10702717', '48.93454967', '10', '4.563792219', '-19.31163198', '28.75639925', '-18.45761877', '33.252666', '-9.248903191', '34.36540071', '47.53562904', '45.7108634', '52.17415927', '30.54990502', '28.35374278', '-16.36076112', '46.88925783', '43.3538644', '-35.81575763', '-18.90265867', '-1.581181915', '36.14118992', '38.27589013', '51.94390501', '47.61306649', '-0.399995771', '11', '34.55468895', '-10.36261454', '-9.778056242', '53.84940846', '53.13233119', '-23.66800444', '51.22937117', '-10.14068384', '-6.496195902', '29.57142745', '-2.666803669', '28.04306149', '25', '-24.70043508', '40.27880968', '29.78610668', '42.95640301', '-18.90112282', '-10.97015456', '-8.25481245', '-9.638801336', '-9.909440925', '35.40233875', '35.30980323', '35.73926206', '35.52394706', '-3.761889863', '39.38316934', '-13.34126151', '-2.475368771', '42.56993205', '28.91053504', '32.92979253', '39.25410903', '-0.871723653', '-15.82168209', '5.517470006', '29.5304898', '33.02434314', '42.84685687', '0.257630327', '-0.2228234', '45.92999947', '46.44566382', '43.65486147', '48.3823364', '51.47143749', '26.49138841', '38.85279954', '2.754193798', '37.19396132', '42.98639722', '-43.62541346', '54.17323366', '32.07700035', '30.60813248', '-11.08318958', '-20.24794729', '52.04800248', '-11.52636513', '35.0621461', '-20.58731044', '-11.09874064', '-18.31117447', '37.21403232', '-18.43232957', '0.548998137', '-8.35102561', '34.54408249', '-1.198008932', '44.82688768', '-11.90352158', '3.207385793', '3.389625544', '30.3054997', '-16.29992418', '-17.67422239', '-5.472423489', '2.727734601', '39.40515161', '45.84513865', '11.19661971', '40.66717303', '-10.1288288', '31.14011906', '-11.33699198', '42.9515239', '-5.798711676', '27.46325843', '49.85514063', '40.52615255', '-13.85555813', '33.28431211', '42.4731373', '-3.431106621', '5', '-7.047265034', '39.48706023', '-2.398700357', '39.06824636', '-1.020500027', '18', '-12.44113808', '-18.05418907', '50.23826213', '10.4216168', '-34.41711527', '44.93176428', '36.18907426', '-9.623062254', '44.28870818', '-1.005268319', '-13.19863186', '-18.69235271', '45.04989173', '-18.78687984', '41.96855078', '40.17907614', '40.44853118', '50.14234501', '21', '7.042916198', '26.38273342', '37.93297382', '54.64598899', '1.083764946', '-6.260290804', '-16.36458931', '-19.80939099', '50.02946976', '44.29441699', '-2.105071957', '-5.519855665', '38.83289665', '-22.010069', '46.46931572', '-24.54882343', '46.94646266', '54.60574916', '37.58843647', '19', '-16.2608971', '14', '-6.928265517', '52.2948916', '1.234738899', '36.40081388', '-6.402224494', '50.3499744', '43.45032795', '51.2561959', '35.77617642', '-19.73127299', '1.63488693', '32.19093588', '38.66234412', '33.82554794', '38.05212158', '49.11875923', '-13.83650197', '51.86558858', '4.852623072', '24.42621636', '34.03490791', '-0.006221399', '-5.654516348', '35.16293041', '52.45029642', '-5.058123274', '38.81388653', '44.01452226', '14.73466935', '31.49879061', '-13.46086848', '36.89955403', '42.35696751', '-7.99445065', '-2.436277763', '48.33046835', '-17.66506344', '-6.36445797', '0.64365928', '51.81780671', '49.75987134', '35.19637699', '49.7904402', '27', '30.98682419', '-11.85156251', '-19.81338725', '-5.990044826', '-0.368576054', '29.27665737', '40.08906458', '40.47299251', '-12.90639375', '53.87618817', '48.19475105', '37.62578923', '-0.198479563', '-3.740018248', '-15.62939639', '52.89309985', '36.10909204', '-11.26775596', '2.433838527', '-16.77810004', '-12.74286445', '32.5067075', '56.16197924', '-12.82889011', '26.54510508', '-21.03731536', '53.15301711', '-11.02995096', '-23.46838168', '49.62575011', '-7.537387378', '-17.07968464', '-7.203747536', '40.58911719', '-9.154338862', '34.79245568', '29.54521074', '-20.36921386', '33.36786974', '45.71683637', '-7.192078843', '-0.047392668', '-19.03033588', '-18.51869077', '-10.88298552', '-4.407431283', '32.73344278', '38.45623068', '32.56652488'}

In [ ]:
# These are obviously need to be transformed:
one_hot = ['gender', 'region_category', 'membership_category', 'feedback', 'used_special_discount', 'offer_application_preference', 'joined_through_referral', 'preferred_offer_types', 'medium_of_operation', 'internet_option']
for c in one_hot:
  churn = pd.concat([churn, pd.get_dummies(churn[c], prefix=c)], axis=1)
  churn = churn.drop(c, axis=1)
churn.head()

,level_0,index,age,joining_date,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,churn,...,joined_through_referral_Yes,preferred_offer_types_Credit/Debit Card Offers,preferred_offer_types_Gift Vouchers/Coupons,preferred_offer_types_Without Offers,medium_of_operation_Both,medium_of_operation_Desktop,medium_of_operation_Smartphone,internet_option_Fiber_Optic,internet_option_Mobile_Data,internet_option_Wi-Fi
0,0,0,30,2821,20,118.390000,10579.56,24,610.360000,1,...,True,False,True,False,False,True,False,False,True,False
1,1,1,55,3368,15,179.420000,22963.05,27,694.650000,0,...,False,True,False,False,False,False,True,False,False,True
2,3,3,18,3368,7,-1035.833706,48913.61,27,1150.093442,0,...,False,True,False,False,False,True,False,False,True,False
3,4,4,28,2845,10,449.770000,20010.02,14,653.040000,0,...,True,True,False,False,True,False,False,True,False,False
4,5,5,45,2996,14,159.170000,48040.07,13,679.070000,0,...,True,False,False,True,False,False,True,True,False,False

In [ ]:
corr = churn.corr()

KeyboardInterrupt: